### ISSUE TITLE
Warning after put siren on gem file

### ISSUE THREAD

**Issue by cleytonmessias** [jcoglan/siren#3]
Hi, 

After i've added `siren` to my gem file, this message started showing when I run some tests or start the rails console.

```
/Users/{user}/.rvm/gems/ruby-2.0.0-p247@project/gems/methodphitamine-1.0.0/lib/methodphitamine/it_class.rb:14: warning: undefining `object_id' may cause serious problems
/Users/{user}/.rvm/gems/ruby-2.0.0-p247@project/gems/methodphitamine-1.0.0/lib/methodphitamine/it_class.rb:14: warning: undefining `__send__' may cause serious problems
```

Can you guys help me ?

Thanks

**Comment by jcoglan** [comment]
This warning doesn't cause any practical problems and can safely be ignored. If you are bothered by it, it's in the `methodphitamine` gem, not in `siren`.
